apiVersion: v1
kind: Service
metadata:
  name: dissertation-service
  labels:
    app: 2020wa86188-app
spec:
  selector:
    app: 2020wa86188-app  # Updated to match metadata label
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32751
